name: "AWS CloudFront"

on:
  push:
    branches:
      - static-website

env:
  BUCKET_NAME: "blockexplorer"
  CDN_ID: "E20QEE87PNORDU"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.NONPROD_AWS_ACCOUNT_ID }}:role/github-dev
          aws-region: us-east-1

      - name: Build Artifacts
        env:
          DOCKER_BUILDKIT: 1
        run: docker build --no-cache --output bucket .

      - name: Uploading Content to AWS
        run: ls -ltr bucket/ && aws s3 sync --delete bucket/ s3://$BUCKET_NAME

      ##- name: CDN Cache Invalidation
      ##  run: aws cloudfront create-invalidation --distribution-id $CDN_ID --paths "/*"
